2023-08-03 11:30:17,147 - ERROR - An error occurred: 
Traceback (most recent call last):
  File "D:\Programming_Files\Auriga\Device Monitoring App\Final_App\device_monitor.py", line 101, in main
    time.sleep(ping_interval)
KeyboardInterrupt
2023-08-03 11:35:05,554 - ERROR - An error occurred: 
Traceback (most recent call last):
  File "D:\Programming_Files\Auriga\Device Monitoring App\Final_App\device_monitor.py", line 102, in main
    time.sleep(ping_interval)
KeyboardInterrupt
2023-08-03 11:47:57,378 - ERROR - Error: User entered an invalid command or incomplete command.
2023-08-03 11:50:32,502 - ERROR - Error: User entered an invalid command or incomplete command.
2023-08-03 11:50:56,735 - ERROR - Error: User entered an invalid IP.
2023-08-03 11:52:47,661 - ERROR - Error: User entered a device ID that already exists.
2023-08-03 11:53:03,063 - ERROR - Error: User entered a device ID that does not exist.
2023-08-18 22:07:22,637 - ERROR - An error occurred: 
Traceback (most recent call last):
  File "D:\Programming_Files\Auriga-Python\Device Monitoring App\Final_App\device_monitor.py", line 103, in main
    time.sleep(ping_interval)
KeyboardInterrupt
